export const CONSTANTS = {
  ASTEROIDS: {
    SPAWN_INTERVAL: 0.8,
    WIDTH: 40,
    HEIGHT: 40,
    BASE_SPEED: 100,
    SPEED_VARIANCE: 150,
    ROT_SPEED_VARIANCE: 0.05
  },

  PLAYER: {
    WIDTH: 40,
    HEIGHT: 40,
    SPEED: 300,
    BOTTOM_OFFSET: 60
  },

  POWERUPS: {
    SPAWN_INTERVAL: 10,
    DURATION: 5,
    WIDTH: 30,
    HEIGHT: 30,
    BASE_SPEED: 100,
    SPEED_VARIANCE: 50
  },

  STARS: {
    COUNT: 300,
    BASE_SPEED: 0.8
  },

  EFFECTS: {
    EXPLOSION_PARTICLES: 25,
    SHAKE_DURATION: 0.6,
    SHAKE_INTENSITY: 6,
    FLASH_FADE_SPEED: 1.2,
    POWER_GLOW_DURATION: 0.6
  },

  SCORING: {
    DIFFICULTY_RAMP_TIME: 10,
    DIFFICULTY_CAP: 4,
    SCORE_MULTIPLIER: 2
  }
};
